### ISSUE TITLE
Maybe remove HTML markup at the top of the SCSS files

### ISSUE THREAD

**Issue by mikeselander** [greenpeace/planet4-presentation-layer#20]
Question of opinion:

We have these massive HTML blobs at the top of the SCSS files.

I see a few problems with this:
1. It massively pollutes the files and makes it so that you have to scroll an indeterminate amount to get to the real, actual code
2. You have to maintain 2 copies of the HTML - one in the actual HTML, and one in the SCSS files
3. We're likely going to dump this once it hits the WP repo anyways
4. It's not getting stripped from the output CSS right now, increasing the size of the compiled file significantly

Should we remove these?

**Comment by kadamwhite** [comment]
I’m in favor of removing, though it might help to ask why it came to be this way

**Comment by 27Bslash6** [comment]
I believe the principle was HTML was added as templates for implementation since front-end HTML+CSS design was isolated from implementation.  @koyan will know if it's still necessary.

**Comment by koyan** [comment]
It was indeed added there only so that backend developers knew what markup to implement in the related plugins/theme. It is not meant to stay there past implementation

**Comment by ashish173** [comment]
@mikeselander Yes, since in the beginning it was very difficult for devs to track the markup for multiple blocks on multiple pages as there is reuse etc. so I came up with this solution for backend devs that the commented markup in scss file should be the single point of truth when it comes to complete markup. 

Also, we have in case of header block some code not showing in the .html file for customisation so it made sense to give the complete version somewhere irrespective of customisations, hence we came up with markup in scss file.

But I do agree it make the size of css file more,

I think when we make the transition from presentation layer to theme we can have a better approach.

**Comment by mikeselander** [comment]
Thanks for the feedback guys - good to know the background. I don't have a clear picture on whether this is still used or if we're treating the HTML as the source of truth. I would advocate for the actual HTML markup as the source of truth since it's being actively tested against but understand if that's not ideal.

**Comment by koyan** [comment]
The developers can bear the weight of taking the markup from the html (instead of the top of the scss file). So, please go on and remove it (the least places we have duplication, the better).
